### ISSUE TITLE
macosx nightly-aarch64-apple-darwin 编译错误

### ISSUE THREAD

**Issue by gqf2008** [js2xxx/ferroc#1]
error[E0308]: mismatched types
    --> /Users/gqf/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ferroc-0.1.3/src/global/thread.rs:64:70
     |
64   |                 let ret = $crate::global::thread::pthread_key_create(&mut key, Some(dtor));
     |                           ------------------------------------------ ^^^^^^^^ expected `*mut u64`, found `&mut u32`
     |                           |
     |                           arguments to this function are incorrect
     |
    ::: /Users/gqf/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ferroc-0.1.3/src/lib.rs:153:1
     |
153  | config_mod!(global_mmap: pub crate::base::Mmap: pthread);
     | -------------------------------------------------------- in this macro invocation
     |
     = note:    expected raw pointer `*mut u64`
             found mutable reference `&mut u32`
note: function defined here
    --> /Users/gqf/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.153/src/unix/mod.rs:1074:12
     |
1074 |     pub fn pthread_key_create(
     |            ^^^^^^^^^^^^^^^^^^
     = note: this error originates in the macro `$crate::thread_init_pthread` which comes from the expansion of the macro `config_mod` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
    --> /Users/gqf/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ferroc-0.1.3/src/global/thread.rs:69:72
     |
69   |                     let _ = $crate::global::thread::pthread_key_delete(key);
     |                             ------------------------------------------ ^^^ expected `u64`, found `u32`
     |                             |
     |                             arguments to this function are incorrect
     |
    ::: /Users/gqf/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ferroc-0.1.3/src/lib.rs:153:1
     |
153  | config_mod!(global_mmap: pub crate::base::Mmap: pthread);
     | -------------------------------------------------------- in this macro invocation
     |
note: function defined here
    --> /Users/gqf/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.153/src/unix/mod.rs:1078:12
     |
1078 |     pub fn pthread_key_delete(key: pthread_key_t) -> ::c_int;
     |            ^^^^^^^^^^^^^^^^^^
     = note: this error originates in the macro `$crate::thread_init_pthread` which comes from the expansion of the macro `config_mod` (in Nightly builds, run with -Z macro-backtrace for more info)
help: you can convert a `u32` to a `u64`
     |
69   |                     let _ = $crate::global::thread::pthread_key_delete(key.into());
     |                                                                           +++++++

error[E0308]: mismatched types
    --> /Users/gqf/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ferroc-0.1.3/src/global/thread.rs:73:67
     |
73   |             let ret = $crate::global::thread::pthread_setspecific(key, data);
     |                       ------------------------------------------- ^^^ expected `u64`, found `u32`
     |                       |
     |                       arguments to this function are incorrect
     |
    ::: /Users/gqf/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ferroc-0.1.3/src/lib.rs:153:1
     |
153  | config_mod!(global_mmap: pub crate::base::Mmap: pthread);
     | -------------------------------------------------------- in this macro invocation
     |
note: function defined here
    --> /Users/gqf/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.153/src/unix/mod.rs:1080:12
     |
1080 |     pub fn pthread_setspecific(key: pthread_key_t, value: *const ::c_void) -> ::c_int;
     |            ^^^^^^^^^^^^^^^^^^^
     = note: this error originates in the macro `$crate::thread_init_pthread` which comes from the expansion of the macro `config_mod` (in Nightly builds, run with -Z macro-backtrace for more info)
help: you can convert a `u32` to a `u64`
     |
73   |             let ret = $crate::global::thread::pthread_setspecific(key.into(), data);
     |                                                                      +++++++

For more information about this error, try `rustc --explain E0308`.
error: could not compile `ferroc` (lib) due to 3 previous errors

**Comment by js2xxx** [comment]
Fixed. Please update the dependency to `^0.1.4` to see the changes.
