### ISSUE TITLE
编译报错：add `#![feature(pointer_is_aligned_to)]` to the crate attributes to enable（加了也没用）

### ISSUE THREAD

**Issue by i18n-now** [js2xxx/ferroc#5]
如图：
add `#![feature(pointer_is_aligned_to)]` to the crate attributes to enable

<img width="1920" alt="image" src="https://github.com/js2xxx/ferroc/assets/145643935/34a8a61f-9da8-48b6-ad4c-d6d62e5fec94">

**Comment by js2xxx** [comment]
抱歉，现在才看到。现在已经修复了，更新到了最新的nightly版本。可以将Cargo.toml依赖源换成GitHub之后重新尝试编译。
```toml
ferroc = {git = "https://github.com/js2xxx/ferroc.git"}
```

**Comment by i18n-now** [comment]
明白，建议发个新版本，方便用
